#!/usr/bin/env bash
# scaffold-onboard/lib/agents.sh
# Managed Codex-facing AGENTS.md section merge. Preserves user-authored
# content outside scaffold-onboard's marker block.

set -u
source "$(dirname "${BASH_SOURCE[0]}")/_helpers.sh"

SF_AGENTS_START="<!-- scaffold-onboard:codex:start -->"
SF_AGENTS_END="<!-- scaffold-onboard:codex:end -->"

sf_agents_managed_block() {
  local manifest_path="${1:-.workspace/pairing.json}"
  local ts
  ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  cat <<EOF
${SF_AGENTS_START}
## Codex shared-workspace guidance

Generated by scaffold-onboard at ${ts}. This managed section may be refreshed; keep custom local instructions outside the marker block.

- Treat \`.workspace/pairing.json\` as the source of truth for AI-workspace vs canonical routing.
- Shared planning state lives in \`MASTER-SPEC.md\`, \`ROADMAP.md\`, \`.claude/memory-bank/\`, and \`.workspace/handoffs/\`.
- Do not create a parallel \`.codex\` memory mirror for scaffold state.
- Use scaffold-onboard for onboarding, memory-bank derivation, roadmap planning, machine-checkable rules, and demo criteria.
- Use scaffold-dev for vertical-slice planning, work-item handoffs, implementation checks, retrospectives, ADRs, runbooks, and changelog entries.
- Before switching between Claude Code and Codex mid-project, run the scaffold-onboard interoperability check/repair helpers or inspect ${manifest_path}.
- Volatile state writes should use scaffold helpers so lock/provenance markers are preserved.
${SF_AGENTS_END}
EOF
}

sf_agents_merge_managed_section() {
  local target="${1:-AGENTS.md}"
  local manifest_path="${2:-.workspace/pairing.json}"
  local block tmp block_file
  block="$(sf_agents_managed_block "$manifest_path")"
  mkdir -p "$(dirname "$target")"
  tmp="$(mktemp "${target}.XXXXXX")"
  block_file="$(mktemp "${target}.block.XXXXXX")"
  printf '%s\n' "$block" > "$block_file"

  if [[ ! -f "$target" ]]; then
    {
      printf '# AGENTS.md\n\n'
      printf '%s\n' "$block"
    } > "$tmp"
    mv "$tmp" "$target"
    rm -f "$block_file"
    return 0
  fi

  if grep -qF "$SF_AGENTS_START" "$target" && grep -qF "$SF_AGENTS_END" "$target"; then
    awk -v start="$SF_AGENTS_START" -v end="$SF_AGENTS_END" -v repl_file="$block_file" '
      index($0, start) {
        while ((getline line < repl_file) > 0) print line
        close(repl_file)
        skipping = 1
        next
      }
      index($0, end) { skipping = 0; next }
      skipping == 1 { next }
      { print }
    ' "$target" > "$tmp"
  else
    {
      cat "$target"
      printf '\n%s\n' "$block"
    } > "$tmp"
  fi

  mv "$tmp" "$target"
  rm -f "$block_file"
}
