#!/usr/bin/env bash
# scaffold/lib/claude-md.sh — two-layer CLAUDE.md generator.
#
# Sources:
#   ${CLAUDE_PLUGIN_DATA}/personal-defaults.md       (user-global)
#   ${CLAUDE_PLUGIN_DATA}/projects/<hash>/claude-md-project.md  (per-repo)
#
# Output:
#   <repo-root>/CLAUDE.md  (with footer-comment timestamp for manual-edit detection)
#
# Sources lib/repo.sh and lib/state.sh.

SF_CMD_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./state.sh
source "${SF_CMD_LIB_DIR}/state.sh"

# ── Path resolution ─────────────────────────────────────────────────────────

# sf_personal_defaults_path — user-global personal-defaults source.
sf_personal_defaults_path() {
  printf '%s/personal-defaults.md' "$(sf_data_dir)"
}

# sf_project_layer_path — per-repo project-specific source.
sf_project_layer_path() {
  printf '%s/claude-md-project.md' "$(sf_project_dir)"
}

# sf_claude_md_path — the generated file inside the working tree.
sf_claude_md_path() {
  printf '%s/CLAUDE.md' "$(sf_repo_root)"
}

# sf_template_path — locate a template inside the plugin install.
# CLAUDE_PLUGIN_ROOT is set by Claude Code at hook/command runtime; falls back
# to relative computation for shell-level testing.
sf_template_path() {
  local name="$1"
  local root="${CLAUDE_PLUGIN_ROOT:-${SF_CMD_LIB_DIR}/..}"
  printf '%s/templates/%s' "$root" "$name"
}

# ── Seeding ─────────────────────────────────────────────────────────────────

# sf_seed_personal_defaults — copy template seed to personal-defaults path
# if missing. Returns 0 if seeded (created), 1 if already existed.
sf_seed_personal_defaults() {
  local target tmpl
  target="$(sf_personal_defaults_path)"
  if [[ -e "$target" ]]; then
    return 1
  fi
  tmpl="$(sf_template_path 'claude-md-personal-defaults.md')"
  mkdir -p "$(dirname "$target")" 2>/dev/null || return 1
  if [[ -r "$tmpl" ]]; then
    cp "$tmpl" "$target"
  else
    printf '%s\n' "## Personal preferences" "" "(your personal defaults — edit me)" > "$target"
  fi
  return 0
}

# sf_seed_project_layer — copy project-layer template seed if missing.
# Substitutes {{project_name}}, {{detected_stack}}, {{test_command}}, {{llm_flag}}.
sf_seed_project_layer() {
  local target tmpl project_name stack test_cmd llm
  target="$(sf_project_layer_path)"
  if [[ -e "$target" ]]; then
    return 1
  fi
  tmpl="$(sf_template_path 'claude-md-project.md.tmpl')"
  mkdir -p "$(dirname "$target")" 2>/dev/null || return 1
  project_name="$(basename "$(sf_repo_root)")"
  stack="$(sf_stack_detect | tr '\n' ' ' | sed 's/ $//')"
  [[ -z "$stack" ]] && stack="(unknown)"
  test_cmd="$(sf_test_command)"
  [[ -z "$test_cmd" ]] && test_cmd="(none detected)"
  llm="$(sf_llm_detect)"
  if [[ -r "$tmpl" ]]; then
    sed -e "s|{{project_name}}|${project_name}|g" \
        -e "s|{{detected_stack}}|${stack}|g" \
        -e "s|{{test_command}}|${test_cmd}|g" \
        -e "s|{{llm_flag}}|${llm}|g" \
        "$tmpl" > "$target"
  else
    printf '## Project: %s\n\n**Stack:** %s\n' "$project_name" "$stack" > "$target"
  fi
  return 0
}

# ── Generation ──────────────────────────────────────────────────────────────

# sf_claude_md_footer_marker — text used as the "generated by" footer marker.
sf_claude_md_footer_marker() {
  printf '<!-- scaffold-claude-md generated-at:'
}

# sf_generate_claude_md — concatenate personal + project layers + footer to
# <repo>/CLAUDE.md. Auto-seeds layers if missing. Refuses to run if state
# has claude_md_managed=false (user opted out).
# Echoes the generated path on success; prints to stderr and returns 1 on error.
sf_generate_claude_md() {
  # Respect opt-out. Read claude_md_managed without the lossy `// empty`
  # default — jq's `// empty` treats boolean `false` as "no value" and would
  # incorrectly fall through, defeating the opt-out.
  local managed
  managed="$(sf_read_state | jq -r '.claude_md_managed' 2>/dev/null)"
  if [[ "$managed" == "false" ]]; then
    echo "scaffold: claude_md_managed=false; skipping generation" >&2
    return 1
  fi

  sf_seed_personal_defaults || true
  sf_seed_project_layer || true

  local personal project target
  personal="$(sf_personal_defaults_path)"
  project="$(sf_project_layer_path)"
  target="$(sf_claude_md_path)"
  local now
  now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local repo_name
  repo_name="$(basename "$(sf_repo_root)")"

  {
    printf '# Personal preferences\n\n'
    printf '<!-- Source: %s -->\n\n' "$personal"
    if [[ -r "$personal" ]]; then cat "$personal"; else printf '_(personal-defaults missing; edit via /scaffold-claude-md-edit personal)_\n'; fi
    printf '\n\n---\n\n'
    printf '# Project: %s\n\n' "$repo_name"
    printf '<!-- Source: %s -->\n\n' "$project"
    if [[ -r "$project" ]]; then cat "$project"; else printf '_(project layer missing; edit via /scaffold-claude-md-edit project)_\n'; fi
    printf '\n\n---\n\n'
    printf '%s %s -->\n' "$(sf_claude_md_footer_marker)" "$now"
    printf '<!-- Do not edit this file directly. Edit the source layers via /scaffold-claude-md-edit. -->\n'
  } > "$target"

  echo "$target"
}

# ── Manual-edit detection ───────────────────────────────────────────────────

# sf_claude_md_footer_timestamp — extract the ISO timestamp from the footer
# marker in the generated CLAUDE.md. Echoes empty if not found / no file.
sf_claude_md_footer_timestamp() {
  local target marker
  target="$(sf_claude_md_path)"
  marker="$(sf_claude_md_footer_marker)"
  [[ -r "$target" ]] || return 1
  # Footer line shape: "<!-- scaffold-claude-md generated-at: 2026-04-26T... -->"
  grep -E "^${marker}" "$target" 2>/dev/null \
    | sed -E 's|.*generated-at: ([^ ]+) -->.*|\1|' \
    | tail -1
}

# sf_claude_md_manually_edited — exits 0 (yes) if mtime of CLAUDE.md is more
# than ~60 seconds newer than its footer timestamp. 1 (no) otherwise.
# Used by /scaffold-claude-md-rebuild to warn before overwriting.
sf_claude_md_manually_edited() {
  local target footer_ts footer_epoch mtime_epoch
  target="$(sf_claude_md_path)"
  [[ -r "$target" ]] || return 1
  footer_ts="$(sf_claude_md_footer_timestamp)"
  [[ -z "$footer_ts" ]] && return 0  # no footer → assume manually authored
  footer_epoch="$(date -u -d "$footer_ts" +%s 2>/dev/null \
    || date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$footer_ts" +%s 2>/dev/null \
    || echo 0)"
  mtime_epoch="$(stat -c %Y "$target" 2>/dev/null || stat -f %m "$target" 2>/dev/null || echo 0)"
  [[ -z "$footer_epoch" || "$footer_epoch" == "0" ]] && return 1
  # Allow 60-second buffer for write timing
  if (( mtime_epoch > footer_epoch + 60 )); then
    return 0
  fi
  return 1
}
